### ISSUE TITLE
Unable to pass 300GB data storage mark.

### ISSUE THREAD

**Issue by Micheletto** [mozilla-services/syncstorage-loadtest#13]
While load testing the Spanner backed GCP infrastructure, the storage reached a peak of 290 GBs and plateaued.  It has fluctuated around this point, and was momentarily at 301GB.  However, it is not accumulating additional storage.

Hitting, and maintaining a storage above 300GBs with a three node Spanner cluster is important to the machine learning that makes Spanner special.

**Comment by pjenvey** [comment]
There's currently nothing in the load test that [triggers BSO deletes](https://github.com/mozilla-services/syncstorage-loadtest/issues/12). However it posts BSOs via batches which stores the data temporarily in a batch table, deleting it after the batch is committed.

I suspect Spanner is [compacting](https://cloud.google.com/bigtable/docs/overview#compactions) this table (maybe even moreso that it's near this special 300gb size). We're probably seeing pre-compaction sizes vs compaction sizes now.

I know the last load test continued hitting Spanner after it was around 300gb but I think we should continue hitting it moreso, I suspect it'll eventually catch up and increase again.
